#!/bin/bash

message() {
  echo "usage:"  
  echo
  echo "  $0 <status|start|stop> [-f]"
  echo "     run systemctl <status|start|stop> in all component services"
  echo
  echo "  $0 <mount|umount>"
  echo "     mount or unmount the chroot"
  echo
  echo "  -f"
  echo "     show full output of the commands"
  echo
  exit 1
}

[ "$1" = "" ] && message && exit 0

if [ "$1" = "mount" ]
then
    export root=/srv/arch
    mkdir -p "$root"
    cd /srv
    mount -o loop,discard,compress=lzo arch.img "$root"
elif [ "$1" = "umount" ]
then
    umount "$root"
else 
    services=("dhcpd4.service" "tftpd.socket" "tftpd.service" "rpc-mountd" "rpc-idmapd")

    for s in ${services[@]}
    do
	if [ "$2" = "-f" ]
	then
	    systemctl $1 $s
	else
	    systemctl $1 $s | head -3
	fi
	
	if [ "$1" = "status" ]
	then
	    echo ""
	fi
    done
fi
