#!/bin/bash

client_install() {
    ##------------------------------------------------------------
    # Client installation:
    echo "installing client image..."

    mv -b /etc/dhcpd.conf{.thinarch,}
    mv -b /usr/lib/systemd/system/tftpd.service{.thinarch,}
    mv -b /etc/exports{.thinarch,}

    truncate -s 2G /srv/arch.img
    mkfs.btrfs /srv/arch.img >/dev/null
    export root=/srv/arch
    mkdir -p "$root"
    mount -o loop,discard,compress=lzo /srv/arch.img "$root"
    pacstrap -c -d "$root" base mkinitcpio-nfs-utils nfs-utils >/dev/null

    sed 's/nfsmount/mount.nfs4/' "$root/usr/lib/initcpio/hooks/net" > "$root/usr/lib/initcpio/hooks/net_nfs4"
    cp $root/usr/lib/initcpio/install/net{,_nfs4}

    cat <<EOF > "$root/etc/ta-mkinitcpio.conf"
MODULES="nfsv4 tg3 e1000e e1000 radeon r8169"
BINARIES="/usr/bin/mount.nfs4"
FILES=""
HOOKS="base udev autodetect keyboard modconf block filesystems net_nfs4"
EOF

    arch-chroot "$root" /usr/bin/mkinitcpio -k /boot/vmlinuz-linux -c /etc/ta-mkinitcpio.conf -g /boot/initramfs-linux.img 

    ##------------------------------------------------------------
    # Client configuration:
    echo "configuring client image..."
    
    ## hostname:
    echo "thinarch" > "$root/etc/hostname"
    cat <<EOF > "$root/etc/hosts"
# /etc/hosts: static lookup table for host names
#

#<ip-address>	<hostname.domain.org>	<hostname>
127.0.0.1	localhost.localdomain	localhost	thinarch
::1		localhost.localdomain	localhost

# End of file     
EOF

    pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S grub >/dev/null
    arch-chroot "$root" grub-mknetdir --net-directory=/boot --subdir=grub >/dev/null

    cat <<EOF > "$root/boot/grub/grub.cfg"
menuentry "Arch Linux Thin Client" {
    linux /vmlinuz-linux quiet rootdelay=1 add_efi_memmap ip=::::::dhcp nfsroot=10.0.0.1:/arch
    initrd /initramfs-linux.img
}
EOF

    pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S xorg-server xorg-server-utils xorg-xinit >/dev/null

    echo -e "\033[0m############################################################"
    echo -e "Things left to do \033[1minside the chroot\033[0m:"
    echo    "    - Make sure to add the extra modules needed by the client machine hardware"
    echo    "      to the $root/etc/ta-mkinitcpio.conf file and run"
    echo -e "      \033[32mmkinitcpio -k /boot/vmlinuz-linux -c /etc/ta-mkinitcpio.conf -g /boot/initramfs-linux.img\033[0m"
    echo    ""
    echo    "    - Install the rest of the packages like DEs, text editors and such."
    echo -e "        \033[32mpacman --root "$root" --dbpath "$root/var/lib/pacman" -S <package ...>\033[0m"
    echo    ""
    echo    "    - Set up your locale, timezone, keymap and follow any other relevant parts of the Installation Guide."
    echo    ""
    echo    "Set your IP address to the one specified in the /etc/dhcp.conf file [default 10.0.0.1]"
    echo    ""
    echo -e "Start the system with \033[32mta-manage start\033[0m"
    echo "############################################################"
}

message() {
  echo "usage:"  
  echo
  echo "  $0 <setup>"
  echo "     execute initial configs"
  echo
  echo "  $0 <mount|umount>"
  echo "     mount or unmount the chroot"
  echo
  echo "  $0 <status|start|stop> [-f]"
  echo "     run systemctl <status|start|stop> in all component services"
  echo
  echo "  -f"
  echo "     show full output of the commands"
  echo
  exit 1
}

[ "$1" = "" ] && message && exit 0

if [ "$1" = "mount" ]
then
    export root=/srv/arch
    mkdir -p "$root"
    mount -o loop,discard,compress=lzo /srv/arch.img "$root"
elif [ "$1" = "umount" ]
then
    umount /srv/arch
else 
    services=("dhcpd4.service" "tftpd.socket" "tftpd.service" "nfs-server.service")

    for s in ${services[@]}
    do
	if [ "$2" = "-f" ]
	then
	    systemctl $1 $s
	else
	    systemctl $1 $s | head -3
	fi
	
	if [ "$1" = "status" ]
	then
	    echo ""
	fi
    done
fi
