#!/bin/sh

export root=/srv/arch

## locale:
sed -i 's/^#\(en_US\.UTF-8 UTF-8\)/\1/' "$root/etc/locale.gen"
sed -i 's/^#\(pt_BR\.UTF-8 UTF-8\)/\1/' "$root/etc/locale.gen"
arch-chroot "$root" locale-gen
echo LANG=en_US.UTF-8 > "$root/etc/locale.conf"

## timezone:
arch-chroot "$root" ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
hwclock --hctosys --localtime

## video drivers
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S xf86-video-ati
#pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S xf86-video-intel

## input drivers
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S xf86-input-synaptics

## desktop environment
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S gtk2-xfce-engine gtk3-xfce-engine thunar thunar-volman xfce4-appfinder xfce4-panel xfce4-session xfce4-settings xfce4-terminal xfconf xfdesktop xfwm4

## fonts
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S ttf-dejavu

## devel tools
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S gcc gedit

## gvfs (mount drives)
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S gvfs

## para manipular pdfs
pacman --noconfirm --root "$root" --dbpath "$root/var/lib/pacman" -S poppler evince

## users
cp ta-prepusers calouros2014-1_analise "$root/root"
arch-chroot "$root" /root/ta-prepusers /root/calouros2014-1_analise
rm "$root/root/ta-prepusers" "$root/root/calouros2014-1_analise"

## other files
cp ta-forAll "$root/root"
